{
  "openapi": "3.0.1",
  "info": {
    "title": "Restful API copy",
    "description": "",
    "version": "1.0.0"
  },
  "tags": [
    {
      "name": "Extract, Load & Transform (V2)",
      "x-i18n": {
        "zh-CN": {
          "name": "Extract, Load & Transform (V2)"
        }
      }
    }
  ],
  "paths": {
    "/v2/etl/merge": {
      "post": {
        "summary": "Merge Data",
        "deprecated": false,
        "description": "You can use this interface to add fields with or without data to an existing collection.<div style=\"padding: 8px;\"><ul style=\"margin-bottom: 0px;\"><li>If you choose to add fields with data, you need to upload the data file to an AWS S3 bucket or a Zilliz Cloud Volume and ensure that the data share the same merge key as the source collection. The merged data will be stored in a new collection that you specify.</li><li>If you choose to add without data, the new fields will be created with null values.</li></ul></div>You need to be a project admin or above to perform this operation. For details, refer to <a href=\"/docs/merge-data\">Merge Data</a>.<br/>",
        "x-i18n": {
          "zh-CN": {
            "summary": "合并数据",
            "description": "您可以使用此接口在指定 Collection 中新增字段并填充数据。<div style=\"padding: 8px;\"><ul style=\"margin-bottom: 0px;\"><li>如果您选择创建字段的同时填充数据，需要将数据文件上传到阿里云 OSS 存储桶或 Zilliz Cloud Volume，并确保数据与源 Collection 的合并键相同。合并后的数据将存储在您指定的新 Collection 中。</li><li>如果您选择仅创建字段但不填充数据，则会创建新的字段并填充 null 值。</li></ul></div>您需要是项目管理员或以上权限才能执行此操作。更多详情，可以参考<a href=\"/docs/merge-data\">合并数据</a>。<br/>"
          }
        },
        "tags": [
          "Extract, Load & Transform (V2)"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "description": "The authentication token should be an API key with appropriate privileges.",
            "required": true,
            "example": "Bearer {{TOKEN}}",
            "schema": {
              "type": "string"
            },
            "x-i18n": {
              "zh-CN": {
                "description": "认证令牌，应为具备适当权限的 API 密钥。"
              }
            },
            "x-i18n-langs": [
              "zh-CN"
            ]
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "oneOf": [
                  {
                    "x-tab-label": "use volume",
                    "type": "object",
                    "properties": {
                      "clusterId": {
                        "type": "string",
                        "description": "Name of the cluster that holds the target collection of this operation.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "本操作目标 Collection 所在集群的名称。"
                          }
                        },
                        "example": "in00-xxxxxxxxxxxxxxxxxx"
                      },
                      "dbName": {
                        "type": "string",
                        "description": "Name of the database that holds the target collection of this operation.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "本操作目标 Collection 所在数据库的名称。"
                          }
                        }
                      },
                      "collectionName": {
                        "type": "string",
                        "description": "Name of the target collection of this operation.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "本操作目标 Collection 的名称。"
                          }
                        }
                      },
                      "destDbName": {
                        "type": "string",
                        "description": "Name of the database that holds the collection to create.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "待创建 Collection 所在数据库的名称。"
                          }
                        }
                      },
                      "destCollectionName": {
                        "type": "string",
                        "description": "Name of the collection to create. This collection will hold the merged data.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "待创建 Collection 的名称。该 Collection 将保存合并后的数据。"
                          }
                        }
                      },
                      "dataSource": {
                        "type": "object",
                        "description": "The data to be merged with the above specified collection. You need to upload the data file in PARQUET format to an AWS S3 bucket or a Zilliz Cloud Volume as the data source and then provide the URL of the data file optionally with the access credentials.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "待与指定 Collection 合并的数据。您需要将 PARQUET 格式的数据文件上传到阿里云 OSS 存储桶或 Zilliz Cloud Volume 作为数据源，并提供数据文件的 URL 及访问凭据（如有）。"
                          }
                        },
                        "properties": {
                          "type": {
                            "type": "string",
                            "description": "The type of the data source. When using a volume, set this parameter to `volume`.",
                            "x-i18n": {
                              "zh-CN": {
                                "description": "数据源的类型。"
                              }
                            },
                            "example": "volume"
                          },
                          "volumeName": {
                            "type": "string",
                            "description": "The name of a Zilliz Cloud Volume that holds the PARQUET file. This parameter applies only when you set `type` to `volume`. For details on how to create a volume, see the documentation for the [Create Volume](/reference/restful/create-volume-v2) operation.",
                            "x-i18n": {
                              "zh-CN": {
                                "description": "Zilliz Cloud 存储点的名称。此参数仅当您将 `type` 设置为 `volume` 时有效。有关创建存储点的详细信息，请参阅 [Create Volume](/reference/restful/create-volume-v2) 操作的文档。"
                              }
                            }
                          },
                          "dataPath": {
                            "type": "string",
                            "description": "The URL of the PARQUET file to merge with the existing collection. ",
                            "x-i18n": {
                              "zh-CN": {
                                "description": "待与指定 Collection 合并的 PARQUET 文件的 URL。"
                              }
                            },
                            "example": "path/to/your/data.parquet"
                          }
                        }
                      },
                      "mergeField": {
                        "type": "string",
                        "description": " The data merging operation is similar to a LEFT JOIN operation in relational database systems, with the merge field serving as the shared key between the source collection and the Parquet file containing column-wise data. You need to provide the name of the shared key as the merge field. The merge field must be present in both the existing collection and the Parquet file. In common cases, you can use the primary key as the merge field.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "数据合并操作类似于关系型数据库中的左连接操作，其合并字段充当源 Collection 和 Parquet 文件之间共享键的角色。您需要提供共享键的名称作为合并字段。合并字段必须在源 Collection 和 Parquet 文件中都存在。在一般情况下，您可以使用主键作为合并字段。"
                          }
                        }
                      },
                      "newFields": {
                        "type": "array",
                        "description": "The schema of the fields to create in the new collection. The schema should be an array of field schemas.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "待创建 Collection 的各字段数据结构。该参数的值应该为字段数据结构数组。"
                          }
                        },
                        "items": {
                          "type": "object",
                          "description": "The schema of a field to add.",
                          "x-i18n": {
                            "zh-CN": {
                              "description": "一个待添加字段的数据结构。"
                            }
                          },
                          "properties": {
                            "fieldName": {
                              "type": "string",
                              "description": "Name of the current field to add.",
                              "x-i18n": {
                                "zh-CN": "待添加字段的名称。"
                              }
                            },
                            "dataType": {
                              "type": "string",
                              "description": "Data type of the current field to add.",
                              "x-i18n": {
                                "zh-CN": "待添加字段的数据类型。"
                              },
                              "enum": [
                                "VARCHAR",
                                "INT8",
                                "INT16",
                                "INT32",
                                "INT64",
                                "FLOAT",
                                "DOUBLE",
                                "BOOL"
                              ]
                            },
                            "params": {
                              "type": "object",
                              "description": "Extra settings for the current field to add.",
                              "x-i18n": {
                                "zh-CN": "待添加字段的详细设置。"
                              },
                              "properties": {
                                "maxLength": {
                                  "type": "integer",
                                  "description": "The maximum length of a VARCHAR field value. This parameter is applicable only when `dataType` is set to `VARCHAR`.",
                                  "x-i18n": {
                                    "zh-CN": {
                                      "description": "VARCHAR 字段的最大长度。该参数仅当 `dataType` 设置为 `VARCHAR` 时可用。"
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    "required": [
                      "clusterId",
                      "dbName",
                      "collectionName",
                      "destDbName",
                      "destCollectionName"
                    ]
                  },
                  {
                    "x-tab-label": "use object storage",
                    "type": "object",
                    "properties": {
                      "clusterId": {
                        "type": "string",
                        "description": "Name of the cluster that holds the target collection of this operation.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "本操作目标 Collection 所在集群的名称。"
                          }
                        },
                        "example": "in00-xxxxxxxxxxxxxxxxxx"
                      },
                      "dbName": {
                        "type": "string",
                        "description": "Name of the database that holds the target collection of this operation.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "本操作目标 Collection 所在数据库的名称。"
                          }
                        }
                      },
                      "collectionName": {
                        "type": "string",
                        "description": "Name of the target collection of this operation.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "本操作目标 Collection 的名称。"
                          }
                        }
                      },
                      "destDbName": {
                        "type": "string",
                        "description": "Name of the database that holds the collection to create.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "待创建 Collection 所在数据库的名称。"
                          }
                        }
                      },
                      "destCollectionName": {
                        "type": "string",
                        "description": "Name of the collection to create. This collection will hold the merged data.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "待创建 Collection 的名称。该 Collection 将保存合并后的数据。"
                          }
                        }
                      },
                      "dataSource": {
                        "type": "object",
                        "description": "The data to be merged with the above specified collection. You need to upload the data file in PARQUET format to an AWS S3 bucket or a Zilliz Cloud Volume as the data source and then provide the URL of the data file optionally with the access credentials.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "待与指定 Collection 合并的数据。您需要将 PARQUET 格式的数据文件上传到阿里云 OSS 存储桶或 Zilliz Cloud Volume 作为数据源，并提供数据文件的 URL 及访问凭据（如有）。"
                          }
                        },
                        "properties": {
                          "type": {
                            "type": "string",
                            "description": "The type of the data source. Set this to `s3` when you use an AWS S3 bucket",
                            "x-i18n": {
                              "zh-CN": {
                                "description": "数据源的类型。如果您选择使用阿里云 OSS 存储桶，请设置为 `oss`。"
                              }
                            }
                          },
                          "dataPath": {
                            "type": "string",
                            "description": "The URL of the PARQUET file to merge with the existing collection. ",
                            "x-i18n": {
                              "zh-CN": {
                                "description": "待与指定 Collection 合并的 PARQUET 文件的 URL。"
                              }
                            }
                          },
                          "credential": {
                            "type": "object",
                            "description": "The credentials to access the bucket that holds the PARQUET file. This parameter applies only when you set `type` to `s3`.",
                            "x-i18n": {
                              "zh-CN": {
                                "description": "存放待合并数据文件的存储桶的访问凭据。此参数仅当您将 `type` 设置为 `oss` 时有效。"
                              }
                            },
                            "properties": {
                              "accessKey": {
                                "type": "string",
                                "description": "The access key of the bucket that holds the PARQUET file.",
                                "x-i18n": {
                                  "zh-CN": {
                                    "description": "存放待合并数据文件的存储桶的访问密钥。"
                                  }
                                }
                              },
                              "secretKey": {
                                "type": "string",
                                "description": "The secret key of the bucket that holds the PARQUET file.",
                                "x-i18n": {
                                  "zh-CN": {
                                    "description": "存放待合并数据文件的存储桶的访问密钥。"
                                  }
                                }
                              }
                            }
                          }
                        }
                      },
                      "mergeField": {
                        "type": "string",
                        "description": "The data merging operation is similar to a LEFT JOIN operation in relational database systems, with the merge field serving as the shared key between the source collection and the Parquet file containing column-wise data. You need to provide the name of the shared key as the merge field. The merge field must be present in both the existing collection and the Parquet file. In common cases, you can use the primary key as the merge field.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "数据合并操作类似于关系型数据库中的左连接操作，合并字段充当源 Collection 和 Parquet 文件之间共享键的角色。您需要提供共享键的名称作为合并字段。合并字段必须在源 Collection 和 Parquet 文件中都存在。在一般情况下，您可以使用主键作为合并字段。"
                          }
                        }
                      },
                      "newFields": {
                        "type": "array",
                        "description": "The schema of the fields to add to the existing collection. The schema should be an array of field schemas.",
                        "x-i18n": {
                          "zh-CN": {
                            "description": "待添加字段的 Schema。该参数应为一个字段 Schema 的数组。"
                          }
                        },
                        "items": {
                          "type": "object",
                          "description": "The schema of a field to add.",
                          "x-i18n": {
                            "zh-CN": {
                              "description": "一个待添加字段的 Schema。"
                            }
                          },
                          "properties": {
                            "fieldName": {
                              "type": "string",
                              "description": "Name of the current field to add.",
                              "x-i18n": {
                                "zh-CN": "待添加字段的名称。"
                              }
                            },
                            "dataType": {
                              "type": "string",
                              "description": "Data type of the current field to add.",
                              "x-i18n": {
                                "zh-CN": "待添加字段的数据类型。"
                              },
                              "enum": [
                                "VARCHAR",
                                "INT8",
                                "INT16",
                                "INT32",
                                "INT64",
                                "FLOAT",
                                "DOUBLE",
                                "BOOL"
                              ]
                            },
                            "params": {
                              "type": "object",
                              "description": "Extra settings for the current field to add.",
                              "x-i18n": {
                                "zh-CN": "待添加字段的详细设置。"
                              },
                              "properties": {
                                "maxLength": {
                                  "type": "integer",
                                  "description": "The maximum length of a VARCHAR field value. This parameter is applicable only when `dataType` is set to `VARCHAR`.",
                                  "x-i18n": {
                                    "zh-CN": {
                                      "description": "VARCHAR 字段的最大长度。该参数仅当 `dataType` 设置为 `VARCHAR` 时可用。"
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    "required": [
                      "clusterId",
                      "dbName",
                      "collectionName",
                      "destDbName",
                      "destCollectionName"
                    ]
                  }
                ]
              },
              "examples": {
                "1": {
                  "summary": "use volume",
                  "x-target-request": "OPTION 1",
                  "value": {
                    "clusterId": "in00-xxxxxxxxxxxxxxx",
                    "dbName": "my_database",
                    "collectionName": "my_collection",
                    "destDbName": "my_database",
                    "destCollectionName": "my_merged_collection",
                    "dataSource": {
                      "type": "volume",
                      "volumeName": "my_volume",
                      "dataPath": "/path/to/your/data.parquet"
                    },
                    "mergeField": "id",
                    "newFields": [
                      {
                        "fieldName": "my_field1",
                        "dataType": "VARCHAR",
                        "params": {
                          "maxLength": 512
                        }
                      }
                    ]
                  }
                },
                "2": {
                  "summary": "use object storage",
                  "x-target-lang": "en-US",
                  "x-target-request": "OPTION 2",
                  "value": {
                    "clusterId": "in00-xxxxxxxxxxxxxxx",
                    "dbName": "my_database",
                    "collectionName": "my_collection",
                    "destDbName": "my_database",
                    "destCollectionName": "my_merged_collection",
                    "dataSource": {
                      "type": "s3",
                      "dataPath": "s3://my-bucket/my_data.parquet",
                      "credential": {
                        "accessKey": "my-access-key",
                        "secretKey": "my-secret-key"
                      }
                    },
                    "mergeField": "id",
                    "newFields": [
                      {
                        "fieldName": "my_field1",
                        "dataType": "VARCHAR",
                        "params": {
                          "maxLength": 512
                        }
                      }
                    ]
                  }
                },
                "3": {
                  "summary": "use object storage",
                  "x-target-lang": "zh-CN",
                  "x-target-request": "OPTION 2",
                  "value": {
                    "clusterId": "in00-xxxxxxxxxxxxxxx",
                    "dbName": "my_database",
                    "collectionName": "my_collection",
                    "destDbName": "my_database",
                    "destCollectionName": "my_merged_collection",
                    "dataSource": {
                      "type": "oss",
                      "dataPath": "oss://my-bucket/my_data.parquet",
                      "credential": {
                        "accessKey": "my-access-key",
                        "secretKey": "my-secret-key"
                      }
                    },
                    "mergeField": "id",
                    "newFields": [
                      {
                        "fieldName": "my_field1",
                        "dataType": "VARCHAR",
                        "params": {
                          "maxLength": 512
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "The ID of the bulk-import job.",
            "x-i18n": {
              "zh-CN": {
                "description": "批量导入任务的 ID。"
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    {
                      "x-tab-label": "success",
                      "type": "object",
                      "properties": {
                        "code": {
                          "description": "Response code.",
                          "x-i18n": {
                            "zh-CN": {
                              "description": "响应码。"
                            }
                          },
                          "type": "integer",
                          "example": 0
                        },
                        "data": {
                          "type": "array",
                          "description": "Response payload which carries the IDs of the created data-merge jobs.",
                          "x-i18n": {
                            "zh-CN": {
                              "description": "响应负载，包含了当前操作创建的数据合并任务的 ID。"
                            }
                          },
                          "items": {
                            "type": "object",
                            "description": "A created data-merge job.",
                            "x-i18n": {
                              "zh-CN": {
                                "description": "一个已创建的数据合并任务。"
                              }
                            },
                            "properties": {
                              "jobId": {
                                "type": "string",
                                "description": "The ID of the current data-merge job.",
                                "x-i18n": {
                                  "zh-CN": {
                                    "description": "当前创建的数据合并任务 ID。"
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    {
                      "x-tab-label": "failure",
                      "description": "Returns an error message.",
                      "x-i18n": {
                        "zh-CN": {
                          "description": "返回错误消息。"
                        }
                      },
                      "x-i18n-langs": [
                        "zh-CN"
                      ],
                      "type": "object",
                      "properties": {
                        "code": {
                          "type": "integer",
                          "description": "Response code.",
                          "x-i18n": {
                            "zh-CN": {
                              "description": "响应码。"
                            }
                          }
                        },
                        "message": {
                          "type": "string",
                          "description": "Error message.",
                          "x-i18n": {
                            "zh-CN": {
                              "description": "错误描述。"
                            }
                          }
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "1": {
                    "summary": "success",
                    "x-target-response": "OPTION 1",
                    "value": {
                      "code": 0,
                      "data": {
                        "jobId": "job-xxxxxxxxxxxxxxxxxxxxx"
                      }
                    }
                  },
                  "2": {
                    "summary": "failure",
                    "x-target-response": "OPTION 1",
                    "x-include-target": [
                      "milvus"
                    ],
                    "value": {
                      "code": 1800,
                      "message": "User hasn't authenticated"
                    }
                  },
                  "3": {
                    "summary": "failure",
                    "x-target-response": "OPTION 2",
                    "x-include-target": [
                      "zilliz"
                    ],
                    "value": {
                      "code": 21119,
                      "message": "The apikey is illegal."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearer": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "servers": []
}